# ext.moz.pubspec.yaml

name: pin2me
description: "Pin your website from any device, any browser! Support Import/Export without sign-in."
# documentation:
homepage: https://johnsiu.com/app/pin2me/
# issue_tracker:
publish_to: 'none'
# repository:
version: 2.1.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  json_preferences: ^2.0.3
  lazy_cache: ^2.0.2
  lazy_extensions: ^2.1.1
  lazy_g_drive: ^2.1.2
  lazy_g_sync: ^2.1.3
  lazy_log: ^2.0.2
  lazy_sign_in: ^2.1.2
  lazy_sign_in_extension: ^2.1.3
  lazy_ui_utils: ^1.0.2
  provider: ^6.1.5+1
  reorderables: ^0.6.0
  theme_provider: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - img/
