# ext.chrome.pubspec.yaml

name: pin2me
description: "Pin your website from any device, any browser! Support Import/Export without sign-in."
# documentation:
homepage: https://johnsiu.com/app/pin2me/
# issue_tracker:
publish_to: 'none'
# repository:
version: 2.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  # cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  http: ^1.0.0
  json_preferences: ^2.0.0
  lazy_cache: ^2.0.0
  lazy_download: ^0.0.2
  lazy_extensions: ^2.0.0
  lazy_g_drive: ^2.0.0
  lazy_g_sync: ^2.1.0
  lazy_log: ^2.0.0
  lazy_sign_in: ^2.1.0
  lazy_sign_in_extension: ^2.1.0
  lazy_ui_utils: ^0.0.2
  provider: ^6.0.3
  reorderables: ^0.6.0
  theme_provider: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - img/