name: pin2me
description: "Pin your website from any device, any browser! Support Import/Export without sign-in."
# documentation:
homepage: https://johnsiu.com/app/pin2me/
# issue_tracker:
publish_to: 'none'
# repository:
version: 1.0.24

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  json_preferences: ^1.0.1
  lazy_cache: ^1.0.0
  lazy_collection: ^0.4.3
  lazy_g_drive: ^1.0.0
  lazy_g_sync: ^1.1.0
  lazy_log: ^1.0.6
  lazy_sign_in: ^1.1.0
  lazy_sign_in_google: ^1.1.0
  provider: ^6.0.3
  reorderables: ^0.5.0
  theme_provider: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - img/